sonar.projectKey=wezva-fintech_payment-build
sonar.organization=wezva-fintech
sonar.sources=.
sonar.exclusions=**/*_test.go,vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out